@extends("base")
@section("encabezado")
    @include("header")
@endsection
@section("contenedor")
    @include("servicios")
    @include("soluciones")
    @include("capacitacion")
    @include("contacto")
@endsection
